### ISSUE TITLE
Don't starting. Even with  FG with USE_TELNET=False

### ISSUE THREAD

**Issue by derifgig** [ttobi/2n-sms-server#4]
Hello. 
Today try to upgrade from version 2.0.2.  
I could not do this.

**Example:**
root@v18:~# /usr/local/bin/2nVoiceBlueSMSServer.py fg
Log: Thu Nov  3 11:06:54 2016    Main: START Application /usr/local/bin/2nVoiceBlueSMSServer.py ...
Log: Thu Nov  3 11:06:54 2016    ---------------------
Log: Thu Nov  3 11:06:54 2016    initSQLite table INFO: (... skiped ... )
Log: Thu Nov  3 11:06:54 2016    initSerialPort try open: /dev/ttyUSB0
Log: Thu Nov  3 11:06:54 2016    initSerialPort: /dev/ttyUSB0 opened OK.
Log: Thu Nov  3 11:06:54 2016    sendTelnetCommand Exception: 'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "/usr/local/bin/2nVoiceBlueSMSServer.py", line 1107, in <module>
    serhandler=VoiceBlueCommunicationHandler()
  File "/usr/local/bin/2nVoiceBlueSMSServer.py", line 280, in __init__
    self.initGSMModules()
  File "/usr/local/bin/2nVoiceBlueSMSServer.py", line 289, in initGSMModules
    self.telnetconn.write(cmd + NL)
AttributeError: 'NoneType' object has no attribute 'write'
----- end of example

Q: we need use only telnet mode ?

**Comment by ttobi** [comment]
Hi,

Seems that the modem not connected through USB serial (the ttyUSB0) or 
if yes, need to setup another port where the modem connected.

I would suggest to use through telnet, it is more comfortable and easier.

Tamas

**Comment by derifgig** [comment]
Hi. :)
I am sure that the modem is OK and running with previous version 5 min ago. 

In log I see that connection OK:
Log: Thu Nov 3 11:06:54 2016 initSerialPort try open: /dev/ttyUSB0
Log: Thu Nov 3 11:06:54 2016 initSerialPort: /dev/ttyUSB0 opened OK.

Is very suspicious line in log:
self.telnetconn.write(cmd + NL)

Why server call method of **self.telnetconn** - where USE_TELNET = false... ???

**Comment by ttobi** [comment]
Good question, maybe a bug, need to be fixed. I will see into that, 
until please use the older version if possible.

tamas

**Comment by derifgig** [comment]
thanks, have a good day

**Comment by rsnastin** [comment]
Hi, I have the same error. Found a solution?
